name: InstaCI

on: 
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"  
      - run: npm ci
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - run: npm install -g surge
      - name: Deploy to the Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain 